proxy_app = "tcp://127.0.0.1:27658"
moniker = "c29r3"
db_backend = "goleveldb"
db_dir = "data"
log_level = "main:info,state:info,*:error"
log_format = "plain"
genesis_file = "config/genesis.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_state_file = "data/priv_validator_state.json"
priv_validator_laddr = ""
node_key_file = "config/node_key.json"
abci = "socket"
prof_laddr = "localhost:6060"
fast_sync = true
filter_peers = false

[p2p]
  laddr = "tcp://0.0.0.0:27656"
  external_address = ""
  seeds = ""
  persistent_peers = "190cb35265860f182e35a3bceeb297082858eebd@35.166.247.98:26656"
  addr_book_file = "config/addrbook.json"
  unconditional_peer_ids = ""
  persistent_peers_max_dial_period = "0s"
  flush_throttle_timeout = "100ms"
  private_peer_ids = ""
  handshake_timeout = "20s"
  dial_timeout = "3s"
  max_num_inbound_peers = 40
  max_num_outbound_peers = 10
  max_packet_msg_payload_size = 1024
  send_rate = 5120000
  recv_rate = 5120000
  upnp = false
  addr_book_strict = true
  pex = true
  seed_mode = false
  allow_duplicate_ip = false

[rpc]
  laddr = "tcp://127.0.0.1:27657"
  cors_allowed_origins = []
  cors_allowed_methods = ["HEAD", "GET", "POST"]
  cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]
  grpc_laddr = ""
  grpc_max_open_connections = 900
  unsafe = false
  max_open_connections = 900
  max_subscription_clients = 100
  max_subscriptions_per_client = 5
  timeout_broadcast_tx_commit = "10s"
  max_body_bytes = 1000000
  max_header_bytes = 1048576
  tls_cert_file = ""
  tls_key_file = ""

[consensus]
  wal_file = "data/cs.wal/wal"
  timeout_propose = "3s"
  timeout_propose_delta = "500ms"
  timeout_prevote = "1s"
  timeout_prevote_delta = "500ms"
  timeout_precommit = "1s"
  timeout_precommit_delta = "500ms"
  timeout_commit = "5s"
  skip_timeout_commit = false
  create_empty_blocks = true
  create_empty_blocks_interval = "0s"
  peer_gossip_sleep_duration = "100ms"
  peer_query_maj23_sleep_duration = "2s"

[mempool]
  recheck = true
  broadcast = true
  wal_dir = ""
  size = 5000
  max_txs_bytes = 1073741824
  cache_size = 10000
  max_tx_bytes = 1048576

[instrumentation]
  prometheus = false
  prometheus_listen_addr = ":26660"
  max_open_connections = 3
  namespace = "tendermint"

[tx_index]
  indexer = "kv"
  index_keys = ""
  index_all_keys = true

[fastsync]
  version = "v0"
